name: Simple Expect Pattern Test
on: workflow_dispatch

jobs:
  expect-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Test Expect Patterns
        continue-on-error: true
        run: |
          nix-shell -p expect --run 'expect -c "
            set timeout 30
            puts \"Testing expect functionality in GitHub Actions...\"
            spawn echo \"Test pattern execution\"
            expect {
              -re {.*Test.*execution.*} {
                puts \"✅ Expect pattern working in GitHub Actions\"
                exit 0
              }
              timeout {
                puts \"❌ Expect timeout\"
                exit 1
              }
            }
          "'

      - name: Ubuntu Fallback
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y expect
          expect -c "
            puts \"✅ Ubuntu expect fallback working\"
            exit 0
          "
